// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cabinet.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditResult = `-- name: CreateAuditResult :one
INSERT INTO audit_results (
  upload_id,
  period_from,
  period_to,
  total_income,
  total_expense,
  net_cash_flow,
  has_cash_gap,
  result
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING upload_id, period_from, period_to, total_income, total_expense, net_cash_flow, has_cash_gap, result, created_at
`

type CreateAuditResultParams struct {
	UploadID     int64          `json:"upload_id"`
	PeriodFrom   pgtype.Date    `json:"period_from"`
	PeriodTo     pgtype.Date    `json:"period_to"`
	TotalIncome  pgtype.Numeric `json:"total_income"`
	TotalExpense pgtype.Numeric `json:"total_expense"`
	NetCashFlow  pgtype.Numeric `json:"net_cash_flow"`
	HasCashGap   bool           `json:"has_cash_gap"`
	Result       []byte         `json:"result"`
}

func (q *Queries) CreateAuditResult(ctx context.Context, arg CreateAuditResultParams) (AuditResult, error) {
	row := q.db.QueryRow(ctx, createAuditResult,
		arg.UploadID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.TotalIncome,
		arg.TotalExpense,
		arg.NetCashFlow,
		arg.HasCashGap,
		arg.Result,
	)
	var i AuditResult
	err := row.Scan(
		&i.UploadID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.TotalIncome,
		&i.TotalExpense,
		&i.NetCashFlow,
		&i.HasCashGap,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash, name, company)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, company, created_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         pgtype.Text `json:"name"`
	Company      pgtype.Text `json:"company"`
}

// sqlc queries for personal cabinet.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Company,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Company,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditResult = `-- name: GetAuditResult :one
SELECT upload_id, period_from, period_to, total_income, total_expense, net_cash_flow, has_cash_gap, result, created_at FROM audit_results WHERE upload_id = $1
`

func (q *Queries) GetAuditResult(ctx context.Context, uploadID int64) (AuditResult, error) {
	row := q.db.QueryRow(ctx, getAuditResult, uploadID)
	var i AuditResult
	err := row.Scan(
		&i.UploadID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.TotalIncome,
		&i.TotalExpense,
		&i.NetCashFlow,
		&i.HasCashGap,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, company, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Company,
		&i.CreatedAt,
	)
	return i, err
}

const listUploadsByUser = `-- name: ListUploadsByUser :many
SELECT
  u.id,
  u.filename,
  u.status,
  u.created_at,
  u.user_id,
  ar.period_from,
  ar.period_to,
  ar.total_income,
  ar.total_expense,
  ar.net_cash_flow,
  ar.has_cash_gap,
  ar.created_at AS audit_created_at
FROM uploads u
LEFT JOIN audit_results ar ON ar.upload_id = u.id
WHERE u.user_id = $1
ORDER BY u.created_at DESC
`

type ListUploadsByUserRow struct {
	ID             int64              `json:"id"`
	Filename       string             `json:"filename"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UserID         string             `json:"user_id"`
	PeriodFrom     pgtype.Date        `json:"period_from"`
	PeriodTo       pgtype.Date        `json:"period_to"`
	TotalIncome    pgtype.Numeric     `json:"total_income"`
	TotalExpense   pgtype.Numeric     `json:"total_expense"`
	NetCashFlow    pgtype.Numeric     `json:"net_cash_flow"`
	HasCashGap     pgtype.Bool        `json:"has_cash_gap"`
	AuditCreatedAt pgtype.Timestamptz `json:"audit_created_at"`
}

func (q *Queries) ListUploadsByUser(ctx context.Context, userID string) ([]ListUploadsByUserRow, error) {
	rows, err := q.db.Query(ctx, listUploadsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUploadsByUserRow
	for rows.Next() {
		var i ListUploadsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Status,
			&i.CreatedAt,
			&i.UserID,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.TotalIncome,
			&i.TotalExpense,
			&i.NetCashFlow,
			&i.HasCashGap,
			&i.AuditCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
