// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditResult struct {
	UploadID     int64              `json:"upload_id"`
	PeriodFrom   pgtype.Date        `json:"period_from"`
	PeriodTo     pgtype.Date        `json:"period_to"`
	TotalIncome  pgtype.Numeric     `json:"total_income"`
	TotalExpense pgtype.Numeric     `json:"total_expense"`
	NetCashFlow  pgtype.Numeric     `json:"net_cash_flow"`
	HasCashGap   bool               `json:"has_cash_gap"`
	Result       []byte             `json:"result"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID           int64              `json:"id"`
	UploadID     int64              `json:"upload_id"`
	OpDate       pgtype.Date        `json:"op_date"`
	Amount       pgtype.Numeric     `json:"amount"`
	Direction    string             `json:"direction"`
	Counterparty pgtype.Text        `json:"counterparty"`
	Inn          pgtype.Text        `json:"inn"`
	Purpose      pgtype.Text        `json:"purpose"`
	Category     pgtype.Text        `json:"category"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Activity     pgtype.Text        `json:"activity"`
}

type Upload struct {
	ID        int64              `json:"id"`
	Filename  string             `json:"filename"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    string             `json:"user_id"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	Company      pgtype.Text        `json:"company"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
