// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"context"
)

type Querier interface {
	CreateAuditResult(ctx context.Context, arg CreateAuditResultParams) (AuditResult, error)
	// sqlc queries. Запусти `make sqlc` для генерации Go-кода.
	CreateUpload(ctx context.Context, filename string) (Upload, error)
	// sqlc queries for personal cabinet.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAuditResult(ctx context.Context, uploadID int64) (AuditResult, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error)
	ListTransactionsByUpload(ctx context.Context, uploadID int64) ([]Transaction, error)
	ListUncategorized(ctx context.Context, uploadID int64) ([]Transaction, error)
	ListUploadsByUser(ctx context.Context, userID string) ([]ListUploadsByUserRow, error)
	SetTransactionCategory(ctx context.Context, arg SetTransactionCategoryParams) error
	SetUploadStatus(ctx context.Context, arg SetUploadStatusParams) error
}

var _ Querier = (*Queries)(nil)
