// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUpload = `-- name: CreateUpload :one

INSERT INTO uploads (filename, status)
VALUES ($1, 'received')
RETURNING id, filename, status, created_at, user_id
`

// sqlc queries. Запусти `make sqlc` для генерации Go-кода.
func (q *Queries) CreateUpload(ctx context.Context, filename string) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload, filename)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Status,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions
  (upload_id, op_date, amount, direction, counterparty, inn, purpose, category, activity)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, upload_id, op_date, amount, direction, counterparty, inn, purpose, category, created_at, activity
`

type InsertTransactionParams struct {
	UploadID     int64          `json:"upload_id"`
	OpDate       pgtype.Date    `json:"op_date"`
	Amount       pgtype.Numeric `json:"amount"`
	Direction    string         `json:"direction"`
	Counterparty pgtype.Text    `json:"counterparty"`
	Inn          pgtype.Text    `json:"inn"`
	Purpose      pgtype.Text    `json:"purpose"`
	Category     pgtype.Text    `json:"category"`
	Activity     pgtype.Text    `json:"activity"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.UploadID,
		arg.OpDate,
		arg.Amount,
		arg.Direction,
		arg.Counterparty,
		arg.Inn,
		arg.Purpose,
		arg.Category,
		arg.Activity,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.OpDate,
		&i.Amount,
		&i.Direction,
		&i.Counterparty,
		&i.Inn,
		&i.Purpose,
		&i.Category,
		&i.CreatedAt,
		&i.Activity,
	)
	return i, err
}

const listTransactionsByUpload = `-- name: ListTransactionsByUpload :many
SELECT id, upload_id, op_date, amount, direction, counterparty, inn, purpose, category, created_at, activity FROM transactions WHERE upload_id = $1 ORDER BY op_date
`

func (q *Queries) ListTransactionsByUpload(ctx context.Context, uploadID int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUpload, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.OpDate,
			&i.Amount,
			&i.Direction,
			&i.Counterparty,
			&i.Inn,
			&i.Purpose,
			&i.Category,
			&i.CreatedAt,
			&i.Activity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncategorized = `-- name: ListUncategorized :many
SELECT id, upload_id, op_date, amount, direction, counterparty, inn, purpose, category, created_at, activity FROM transactions WHERE upload_id = $1 AND category IS NULL
`

func (q *Queries) ListUncategorized(ctx context.Context, uploadID int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listUncategorized, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.OpDate,
			&i.Amount,
			&i.Direction,
			&i.Counterparty,
			&i.Inn,
			&i.Purpose,
			&i.Category,
			&i.CreatedAt,
			&i.Activity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionCategory = `-- name: SetTransactionCategory :exec
UPDATE transactions SET category = $2 WHERE id = $1
`

type SetTransactionCategoryParams struct {
	ID       int64       `json:"id"`
	Category pgtype.Text `json:"category"`
}

func (q *Queries) SetTransactionCategory(ctx context.Context, arg SetTransactionCategoryParams) error {
	_, err := q.db.Exec(ctx, setTransactionCategory, arg.ID, arg.Category)
	return err
}

const setUploadStatus = `-- name: SetUploadStatus :exec
UPDATE uploads SET status = $2 WHERE id = $1
`

type SetUploadStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetUploadStatus(ctx context.Context, arg SetUploadStatusParams) error {
	_, err := q.db.Exec(ctx, setUploadStatus, arg.ID, arg.Status)
	return err
}
